name: CI/CD

on:
  pull_request:
    branches: main

jobs:
  cicd:
    name: swift-ci
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@v1
    - run: xcode-select -s /Applications/Xcode_14.1.app/Contents/Developer/
    - name: swift-ci
      run: swift run --package-path .github/workflows/cicd
