name: CI/CD

on:
  pull_request:
    branches: main

jobs:
  cicd:
    name: swift-ci
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: swift-ci
      run: swift run .github/workflows/cicd
